spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/finance_db?sslmode=disable
    username: finance_user
    password: finance_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 18080

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000